version: '3.8'

services:
  collection:
    image: buzurgmexrubon/collection
    container_name: "collection"
    restart: always
    ports:
      - "8080:80"
    networks:
      - web

networks:
  web:
    external: true
