name: CI/CD Pipeline (Dev)

on:
  push:
    branches: [ dev ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd CollectionManagement/
        dotnet restore CollectionManagement.sln
    - name: Build
      run: |
        cd CollectionManagement/
        dotnet build CollectionManagement.sln --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd CollectionManagement/
        dotnet restore CollectionManagement.sln
    - name: Test
      run: |
        cd CollectionManagement/
        dotnet test --configuration Release
